{% set name = "ipyaggrid" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyaggrid-{{ version }}.tar.gz
  sha256: e31faff875887a1754f714307e76b925afcd4171e69f0f5859253b4189a442dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.7.9
    - jupyterlab >=3.0.0,<4.0.0
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - ipywidgets >=7.4.0
    - pandas
    - simplejson >=3.13.2

test:
  imports:
    - ipyaggrid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/widgetti/ipyaggrid
  summary: Jupyter widget - ag-grid in the notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maartenbreddels
    - mariobuikhuizen
    - LeoCo
